const { failed } = require("../utils/errorHandler");


exports.verifyEmail = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.sendOTP = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.resetPassword = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.resetPasswordToken = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}