const { failed } = require("../utils/errorHandler")


exports.createBooking = async(req, res)=>{
    try{
        
    }catch(err){
        failed(res, err);
    }
}
exports.updateBooking = async(req, res)=>{
    try{
        
    }catch(err){
        failed(res, err);
    }
}
exports.extendBooking = async(req, res)=>{
    try{
        
    }catch(err){
        failed(res, err);
    }
}
exports.cancelBooking = async(req, res)=>{
    try{
        
    }catch(err){
        failed(res, err);
    }
}