const { failed } = require("../utils/errorHandler");



exports.addRoom = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.updateRoom = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.removeRoom = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}